import { test, expect } from '@playwright/test'

test.use({ channel: 'chrome' })

async function start(page) {
  await page.goto('/gallery/midnight-dispatch?debug')
  await expect(page.locator('.midnight-canvas')).toBeVisible()
  await page.getByRole('button', { name: 'Start your shift' }).click()
  await expect(page.locator('.midnight')).toHaveAttribute('data-phase', 'playing')
}

test('start screen, walking, entering, driving, braking and exiting', async ({ page }, info) => {
  const errors = []
  page.on('pageerror', (e) => errors.push(e.message))
  await page.goto('/gallery/midnight-dispatch?debug')
  await expect(page.getByRole('button', { name: 'Start your shift' })).toBeVisible()
  await page.screenshot({ path: info.outputPath('desktop-intro.png') })
  await page.getByRole('button', { name: 'Start your shift' }).click()
  await page.keyboard.down('KeyW')
  await page.waitForFunction(() => window.__midnight.state().player.z < 15)
  await page.keyboard.up('KeyW')
  await page.keyboard.press('KeyE')
  await expect(page.locator('.midnight')).toHaveAttribute('data-driving', 'true')
  await page.keyboard.down('KeyW')
  await page.waitForFunction(() => window.__midnight.state().car.speed > 14)
  await page.keyboard.press('KeyE')
  await expect(page.locator('.midnight')).toHaveAttribute('data-driving', 'true')
  await page.keyboard.up('KeyW')
  await page.keyboard.down('Space')
  await page.waitForFunction(() => { const c = window.__midnight.state().car; return Math.hypot(c.vx, c.vz) < 1 })
  await page.keyboard.up('Space')
  await page.keyboard.press('KeyE')
  await expect(page.locator('.midnight')).toHaveAttribute('data-driving', 'false')
  await page.screenshot({ path: info.outputPath('desktop-play.png') })
  expect(errors).toEqual([])
})

test('the first delivery is achievable with real keyboard input', async ({ page }, info) => {
  await start(page)
  await page.keyboard.press('KeyE')
  await page.keyboard.down('KeyW')
  await page.waitForFunction(() => window.__midnight.state().car.z < -29, null, { timeout: 12000 })
  await page.keyboard.up('KeyW')
  await page.keyboard.down('Space')
  await page.waitForFunction(() => window.__midnight.state().job === 1, null, { timeout: 12000 })
  await page.keyboard.up('Space')
  await expect(page.locator('.md-dispatch h2')).toHaveText('RADIO STATION')
  await expect(page.locator('.md-cash')).toContainText('600')
  await page.screenshot({ path: info.outputPath('first-delivery.png') })
  const metrics = await page.evaluate(() => window.__midnight.metrics())
  expect(metrics.calls).toBeLessThan(70)
  await info.attach('render-metrics', { body: JSON.stringify(metrics), contentType: 'application/json' })
})

test('pause and loss of focus freeze the clock and release held controls', async ({ page }) => {
  await start(page)
  await page.keyboard.down('KeyW')
  await page.keyboard.press('Escape')
  const paused = await page.evaluate(() => window.__midnight.state())
  await page.waitForTimeout(300)
  expect(await page.evaluate(() => window.__midnight.state().time)).toBe(paused.time)
  await page.keyboard.up('KeyW')
  await page.getByRole('button', { name: 'Back to the streets', exact: true }).last().click()
  const z = await page.evaluate(() => window.__midnight.state().player.z)
  await page.waitForTimeout(250)
  expect(await page.evaluate(() => window.__midnight.state().player.z)).toBe(z)
  await page.evaluate(() => window.dispatchEvent(new Event('blur')))
  await expect(page.locator('.midnight')).toHaveAttribute('data-phase', 'paused')
  await page.getByRole('button', { name: 'New shift', exact: true }).click()
  await expect(page.locator('.midnight')).toHaveAttribute('data-phase', 'playing')
  expect(await page.evaluate(() => window.__midnight.state().car.health)).toBe(100)
  expect(await page.evaluate(() => window.__midnight.state().job)).toBe(0)
})

test('opposite inputs cancel, reduced motion applies, and leaving cleans up', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await start(page)
  await expect(page.locator('.midnight')).toHaveClass(/midnight--calm/)
  await page.keyboard.down('KeyW')
  await page.keyboard.down('KeyS')
  const before = await page.evaluate(() => window.__midnight.state().player.z)
  await page.waitForTimeout(250)
  expect(await page.evaluate(() => window.__midnight.state().player.z)).toBe(before)
  await page.keyboard.up('KeyW')
  await page.keyboard.up('KeyS')
  await page.getByRole('link', { name: '← Lab', exact: true }).click()
  await expect(page).toHaveURL(/\/gallery$/)
  await expect(page.locator('.midnight')).toHaveCount(0)
  expect(await page.evaluate(() => window.__midnight)).toBeUndefined()
  await expect(page.locator('.carousel-card')).toHaveCount(21)
})

test('mobile touch controls work and fit within the viewport', async ({ browser }, info) => {
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 2 })
  const page = await context.newPage()
  await start(page)
  await page.getByRole('button', { name: 'Enter car', exact: true }).click()
  await expect(page.locator('.midnight')).toHaveAttribute('data-driving', 'true')
  const forward = page.getByRole('button', { name: 'Forward', exact: true })
  const rect = await forward.boundingBox()
  expect(rect.width).toBeGreaterThanOrEqual(44)
  expect(rect.height).toBeGreaterThanOrEqual(44)
  const cdp = await context.newCDPSession(page)
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: rect.x + rect.width / 2, y: rect.y + rect.height / 2, id: 1 }] })
  await page.waitForFunction(() => window.__midnight.state().car.speed > 12)
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
  await page.getByRole('button', { name: 'Pause', exact: true }).click()
  await page.getByRole('button', { name: 'Back to the streets', exact: true }).last().click()
  const bounds = await page.locator('.md-touch').boundingBox()
  expect(bounds.x).toBeGreaterThanOrEqual(0)
  expect(bounds.x + bounds.width).toBeLessThanOrEqual(390)
  await page.screenshot({ path: info.outputPath('mobile-play.png') })
  await context.close()
})

test('WebGL context loss leaves a retry action and Lab exit', async ({ page }) => {
  await start(page)
  await page.locator('.midnight-canvas').evaluate((canvas) => canvas.dispatchEvent(new Event('webglcontextlost', { cancelable: true })))
  await expect(page.getByRole('button', { name: 'Try again' })).toBeVisible()
  await expect(page.getByRole('link', { name: '← Lab', exact: true })).toBeVisible()
})
