import { test, expect } from '@playwright/test'

async function start(page) {
  await page.goto('/gallery/midnight-dispatch?debug', { waitUntil: 'domcontentloaded' })
  await page.getByRole('button', { name: 'Start your shift', exact: true }).click()
  await expect(page.locator('.midnight')).toHaveAttribute('data-phase', 'playing')
}
async function travel(page, x, z) { await page.evaluate(([px, pz]) => window.__midnight.travel(px, pz), [x, z]) }
async function deliver(page, count = 1) {
  if (!(await page.evaluate(() => window.__midnight.state().driving))) await page.keyboard.press('KeyE')
  for (let i = 0; i < count; i++) {
    const before = await page.evaluate(() => { const s = window.__midnight.state(); return { completed: s.completed, target: s.mission.points[s.mission.stage] } })
    await travel(page, before.target.x, before.target.z)
    await page.waitForFunction((n) => window.__midnight.state().completed > n, before.completed)
  }
}
async function panel(page, name) {
  if (!(await page.getByRole('dialog').count())) await page.getByRole('button', { name: 'Open city network', exact: true }).click()
  await page.getByRole('button', { name, exact: true }).click()
}
async function close(page) { await page.getByRole('button', { name: 'Close city network', exact: true }).click() }

test('earned cash buys a usable weapon, reloads it, and survives a browser reload', async ({ page }, info) => {
  const errors = []; page.on('pageerror', (e) => errors.push(e.message))
  await start(page)
  await deliver(page)
  await travel(page, 0, -32)
  await page.keyboard.press('KeyE')
  await panel(page, 'Armory')
  await page.locator('[data-item="pistol"]').getByRole('button', { name: 'Buy', exact: true }).click()
  await expect(page.locator('.md-wallet strong')).toHaveText('$150')
  await expect(page.locator('[data-item="pistol"]')).toContainText('OWNED')
  await page.screenshot({ path: info.outputPath('armory-purchased.png') })
  await close(page)
  await page.keyboard.down('KeyF')
  await page.waitForFunction(() => window.__midnight.state().weapons.pistol.loaded < 12)
  await page.keyboard.up('KeyF')
  await page.keyboard.press('KeyR')
  await page.waitForFunction(() => window.__midnight.state().weapons.pistol.loaded === 12)
  const ammo = await page.evaluate(() => window.__midnight.state().weapons.pistol)
  expect(ammo.reserve).toBeLessThan(36)
  await page.keyboard.press('Escape')
  await page.reload({ waitUntil: 'domcontentloaded' })
  await expect(page.locator('.md-save-note')).toContainText('$150')
  await page.getByRole('button', { name: 'Start your shift', exact: true }).click()
  const saved = await page.evaluate(() => window.__midnight.state())
  expect(saved.weapons.pistol).toEqual(ammo)
  expect(saved.cash).toBe(150)
  expect(saved.job).toBe(1)
  expect(errors).toEqual([])
})

test('three jobs fund a faster car that can be bought, driven and retained', async ({ page }, info) => {
  await start(page); await deliver(page, 3)
  expect(await page.evaluate(() => window.__midnight.state().phase)).toBe('playing')
  await travel(page, -8, 0)
  await panel(page, 'Garage')
  await page.locator('[data-item="runner"]').getByRole('button', { name: 'Buy', exact: true }).click()
  await expect(page.locator('.md-wallet strong')).toHaveText('$1,050')
  await page.screenshot({ path: info.outputPath('garage-purchased.png') })
  await close(page)
  expect(await page.evaluate(() => window.__midnight.state().car.model)).toBe('runner')
  await travel(page, 0, 168)
  await page.keyboard.down('KeyW')
  await page.waitForFunction(() => window.__midnight.state().car.speed > 34)
  await page.keyboard.up('KeyW')
  await page.keyboard.press('Escape')
  await page.reload({ waitUntil: 'domcontentloaded' })
  await page.getByRole('button', { name: 'Start your shift', exact: true }).click()
  expect(await page.evaluate(() => window.__midnight.state().car.model)).toBe('runner')
})

test('contracts, district GPS and atmospheric themes work through the city menu', async ({ page }, info) => {
  await start(page)
  await panel(page, 'Contracts')
  await page.locator('.md-product').filter({ hasText: 'LAST TRAIN HOME' }).getByRole('button', { name: 'Accept job' }).click()
  expect(await page.evaluate(() => window.__midnight.state().mission.type)).toBe('taxi')
  await panel(page, 'City map')
  await page.screenshot({ path: info.outputPath('expanded-map.png') })
  await page.getByRole('button', { name: 'DUST COUNTY' }).click()
  expect(await page.evaluate(() => window.__midnight.state().waypoint.id)).toBe('desert')
  await panel(page, 'Career')
  await page.getByRole('button', { name: 'Golden hour', exact: true }).click()
  await close(page)
  await travel(page, 112, -112)
  await expect(page.locator('.md-district')).toContainText('DUST COUNTY')
  await page.waitForTimeout(800) // Allow the follow camera to settle before capturing the district.
  await page.screenshot({ path: info.outputPath('desert-sunset.png') })
  expect(await page.evaluate(() => window.__midnight.state().theme)).toBe('sunset')
  await panel(page, 'Career')
  await page.getByRole('button', { name: 'Rain city', exact: true }).click()
  await close(page)
  await page.screenshot({ path: info.outputPath('rain-city.png') })
})

test('remote purchases are unavailable and the GPS leads to the required shop', async ({ page }) => {
  await start(page)
  await panel(page, 'Armory')
  await expect(page.locator('[data-item="pistol"] button')).toBeDisabled()
  await page.getByRole('button', { name: 'Set GPS' }).click()
  expect(await page.evaluate(() => window.__midnight.state().waypoint.id)).toBe('armory')
  await expect(page.getByRole('dialog')).toHaveCount(0)
})

test('shop markers explain purchasing and the expanded garage catalog is visible', async ({ page }) => {
  await start(page)
  await expect(page.locator('.md-shop-guide')).toContainText('G garage · A armory · GPS in B')
  await travel(page, -8, 0)
  await expect(page.locator('.md-shop-guide')).toContainText('Arrived · stop, then buy with B')
  await panel(page, 'Garage')
  await expect(page.locator('[data-item]')).toHaveCount(10)
})

test('a purchased gun completes an armed contract and earns its reward', async ({ page }, info) => {
  await start(page); await deliver(page, 2); await travel(page, 0, -32)
  await page.keyboard.press('KeyE')
  await panel(page, 'Armory')
  await page.locator('[data-item="pistol"]').getByRole('button', { name: 'Buy', exact: true }).click()
  await panel(page, 'Contracts')
  await page.locator('.md-product').filter({ hasText: 'HARBOR CLEANUP' }).getByRole('button', { name: 'Accept job' }).click()
  await travel(page, -168, 106)
  await page.waitForTimeout(800) // Capture the encounter after the follow camera reaches the harbor.
  await page.keyboard.down('KeyF')
  await page.waitForFunction(() => window.__midnight.state().enemies.some((e) => e.health < 90))
  await expect(page.locator('.md-ammo strong')).not.toHaveText('12')
  await page.screenshot({ path: info.outputPath('harbor-combat.png') })
  await page.waitForFunction(() => window.__midnight.state().completed === 3)
  await page.keyboard.up('KeyF')
  expect(await page.evaluate(() => window.__midnight.state().cash)).toBe(3000)
  await expect(page.locator('.midnight')).toHaveAttribute('data-phase', 'playing')
})

test('mobile catalog scrolls, purchases and touch firing fit in a narrow viewport', async ({ browser }, info) => {
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 2 })
  const page = await context.newPage()
  await start(page); await deliver(page); await travel(page, 0, -32)
  await page.getByRole('button', { name: 'Exit car', exact: true }).click()
  await panel(page, 'Armory')
  const dialog = await page.getByRole('dialog').boundingBox()
  expect(dialog.x).toBeGreaterThanOrEqual(0); expect(dialog.x + dialog.width).toBeLessThanOrEqual(390)
  await page.locator('[data-item="pistol"]').getByRole('button', { name: 'Buy', exact: true }).click()
  await page.locator('[data-item="shotgun"]').scrollIntoViewIfNeeded()
  await expect(page.locator('[data-item="shotgun"]')).toBeVisible()
  await page.screenshot({ path: info.outputPath('mobile-armory.png') })
  await close(page)
  const trigger = page.getByRole('button', { name: 'Fire weapon', exact: true })
  const bounds = await trigger.boundingBox()
  expect(bounds.width).toBeGreaterThanOrEqual(44); expect(bounds.height).toBeGreaterThanOrEqual(44)
  const cdp = await context.newCDPSession(page)
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: bounds.x + bounds.width / 2, y: bounds.y + bounds.height / 2, id: 1 }] })
  await page.waitForFunction(() => window.__midnight.state().weapons.pistol.loaded < 12)
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
  await page.screenshot({ path: info.outputPath('mobile-combat.png') })
  await context.close()
})
